Repository amfoss/TempleApp, pull requests merged in 2019-07, with the labels that each got.

#68 chore: Update README.md
  README.md
Labels: chore

#69 chore: Store the dimensions into dimens resource file
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/delete_data.xml
  app/src/main/res/layout/insert_data.xml
  app/src/main/res/layout/layout_row_view.xml
  app/src/main/res/layout/read_all.xml
  app/src/main/res/layout/read_data.xml
  app/src/main/res/layout/update_data.xml
  app/src/main/res/values/dimens.xml
Labels: chore

#72 feat: New username insertion and updation
  app/src/main/java/org/amfoss/templeapp/activities/InsertData.java
  app/src/main/java/org/amfoss/templeapp/activities/UpdateData.java
Labels: feature

#71 chore: Add Data binding
  README.md
  app/build.gradle
  app/src/main/java/org/amfoss/templeapp/activities/DeleteData.java
  app/src/main/java/org/amfoss/templeapp/activities/InsertData.java
  app/src/main/java/org/amfoss/templeapp/activities/MainActivity.java
  app/src/main/java/org/amfoss/templeapp/activities/ReadAllData.java
  app/src/main/java/org/amfoss/templeapp/activities/ReadSingleData.java
  app/src/main/java/org/amfoss/templeapp/activities/UpdateData.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/delete_data.xml
  app/src/main/res/layout/insert_data.xml
  app/src/main/res/layout/layout_row_view.xml
  app/src/main/res/layout/read_all.xml
  app/src/main/res/layout/read_data.xml
  app/src/main/res/layout/update_data.xml
  app/src/main/res/values/strings.xml
Labels: chore

#83 fix: Removed non functioning edit texts
  app/src/main/java/org/amfoss/templeapp/activities/InsertData.java
Labels: fix

#82 fix: editTexts for amount only takes numbers
  app/src/main/res/layout/insert_data.xml
  app/src/main/res/layout/update_data.xml
Labels: fix

#84 fix: App bar label is minimized on orientation change
  app/src/main/AndroidManifest.xml
Labels: fix

#85 fix: Fixes UI issue in ReadAll Activity
  app/src/main/res/drawable/ic_circle.xml
  app/src/main/res/layout/layout_row_view.xml
  app/src/main/res/values/dimens.xml
Labels: fix

#86 fix: Fixes crash in ReadAll Activity
  app/src/main/java/org/amfoss/templeapp/activities/ReadAllData.java
  app/src/main/java/org/amfoss/templeapp/adapter/MyArrayAdapter.java
Labels: fix

#88 fix: Scroll functionality enabled
  app/src/main/res/layout/activity_main.xml
Labels: fix

#89 fix: Toast Duration
  app/src/main/java/org/amfoss/templeapp/activities/DeleteData.java
  app/src/main/java/org/amfoss/templeapp/activities/InsertData.java
  app/src/main/java/org/amfoss/templeapp/activities/MainActivity.java
  app/src/main/java/org/amfoss/templeapp/activities/ReadAllData.java
  app/src/main/java/org/amfoss/templeapp/activities/ReadSingleData.java
  app/src/main/java/org/amfoss/templeapp/activities/UpdateData.java
Labels: fix
