Repository amfoss/TempleApp, pull requests merged in 2019-08, with the labels that each got.

#97 fix: updated URL of backend
  app/src/main/java/org/amfoss/templeapp/json_api/Controller.java
Labels: fix

#100 fix: Rearrangement in Add Pooja/Donation
  app/src/main/res/layout/insert_data.xml
Labels: fix

#101 fix: Replaced User ID with the Employee ID
  app/src/main/res/layout/delete_data.xml
  app/src/main/res/layout/insert_data.xml
  app/src/main/res/layout/read_data.xml
  app/src/main/res/layout/update_data.xml
  app/src/main/res/values/strings.xml
Labels: fix

#104 fix: Edit text for Amount remains even after multiple changes in activities.
  app/src/main/java/org/amfoss/templeapp/activities/InsertData.java
Labels: fix

#103 fix: Dimensions edited
  app/src/main/res/layout/delete_data.xml
  app/src/main/res/layout/read_data.xml
Labels: fix

#106 fix: Changed Alert dialogue messages
  app/src/main/res/values/strings.xml
Labels: fix

#109 chore: Spotless
  app/build.gradle
Labels: chore

#108 fix: Edited the toast messages in the search section
  app/src/main/java/org/amfoss/templeapp/activities/ReadSingleData.java
  app/src/main/res/values/strings.xml
Labels: fix

#110 fix: Deleted unwanted message
  app/src/main/java/org/amfoss/templeapp/activities/InsertData.java
  app/src/main/java/org/amfoss/templeapp/activities/UpdateData.java
  app/src/main/res/layout/insert_data.xml
  app/src/main/res/layout/update_data.xml
Labels: fix

#111 chore: replaced app icon
  app/src/main/ic_launcher-web.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/ic_launcher_background.xml
Labels: chore

#113 fix: corrected heading of ReadAll
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/amfoss/templeapp/activities/ReadAllData.java
  app/src/main/res/values/strings.xml
  build.gradle
Labels: fix

#115 fix: Refactored the app code
  app/src/main/res/values/strings.xml
Labels: fix

#118 feat: Revamp the UI of the Main Activity for better UI/UX
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/amfoss/templeapp/activities/MainActivity.java
  app/src/main/java/org/amfoss/templeapp/ui/main/HomeActivity.java
  app/src/main/java/org/amfoss/templeapp/ui/main/PageViewModel.java
  app/src/main/java/org/amfoss/templeapp/ui/main/PlaceholderFragment.java
  app/src/main/java/org/amfoss/templeapp/ui/main/SectionsPagerAdapter.java
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_donate.xml
  app/src/main/res/drawable/ic_log_out.xml
  app/src/main/res/drawable/ic_man.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/drawable/ic_sort.xml
  app/src/main/res/drawable/side_nav_bar.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/app_bar_home.xml
  app/src/main/res/layout/content_home.xml
  app/src/main/res/layout/fragment_tabbed_activty.xml
  app/src/main/res/layout/nav_header_home.xml
  app/src/main/res/menu/activity_home_drawer.xml
  app/src/main/res/menu/home.xml
  app/src/main/res/menu/list_menu.xml
  app/src/main/res/values-v21/styles.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature

#120 chore: Update README.md
  README.md
Labels: chore

#124 chore: Migrated to Androidx
  app/build.gradle
  app/src/main/java/org/amfoss/templeapp/activities/DeleteData.java
  app/src/main/java/org/amfoss/templeapp/activities/InsertData.java
  app/src/main/java/org/amfoss/templeapp/activities/MainActivity.java
  app/src/main/java/org/amfoss/templeapp/activities/ReadAllData.java
  app/src/main/java/org/amfoss/templeapp/activities/ReadSingleData.java
  app/src/main/java/org/amfoss/templeapp/activities/UpdateData.java
  app/src/main/java/org/amfoss/templeapp/json_api/Controller.java
  app/src/main/java/org/amfoss/templeapp/json_api/InternetConnection.java
  app/src/main/java/org/amfoss/templeapp/ui/main/HomeActivity.java
  app/src/main/java/org/amfoss/templeapp/ui/main/PageViewModel.java
  app/src/main/java/org/amfoss/templeapp/ui/main/PlaceholderFragment.java
  app/src/main/java/org/amfoss/templeapp/ui/main/SectionsPagerAdapter.java
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/app_bar_home.xml
  app/src/main/res/layout/content_home.xml
  app/src/main/res/layout/fragment_tabbed_activty.xml
  app/src/main/res/layout/insert_data.xml
  app/src/main/res/layout/layout_row_view.xml
  app/src/main/res/layout/update_data.xml
  app/src/main/res/menu/list_menu.xml
  gradle.properties
Labels: chore
